"use client";

import { useCallback, useMemo, useRef, useState } from "react";
import JSZip from "jszip";
import { templates } from "./templates";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

type TreeNode = {
  name: string;
  path: string;
  type: "file" | "folder";
  /** Depth in the tree (root = 0) */
  depth: number;
};

// ---------------------------------------------------------------------------
// Tree Parser
// ---------------------------------------------------------------------------

const TREE_CONNECTORS = /[├└┌┐┘│─││├┤┬┴┼\u2502\u250c\u2510\u2514\u2518\u251c\u2524\u252c\u2534\u253c\u2500\u2520\u252e\u2530\u256c\u2528\u2560\u2561\u2562\u2563\u2564\u2565\u2566\u2567\u2568\u2569\u256a\u256b\u256d\u256e\u256f\u2570\u2571\u2572\u2573]/g;

/** Strip tree-drawing characters, comments, and whitespace from a name. */
function cleanName(raw: string): string {
  return raw
    .replace(/#.*$/, "")
    .replace(/--\s*$/, "")
    .replace(/`--\s*$/, "")
    .replace(TREE_CONNECTORS, "")
    .replace(/\t/g, "")
    .trim();
}

/**
 * Detect the tree prefix up to the connector character.
 * Handles: "│   ├──", "├──", "|   +--", "    └──", "  |--", etc.
 */
function parseLine(rawLine: string): { prefixLen: number; name: string } | null {
  // Match the connector part: optional prefix (pipes + spaces), then a
  // branching connector (├──, └──, |--, `--, +--, etc.), then the name.
  const m = rawLine.match(
    /^([\s│|]*)(?:[├└┌┐└┘]──|[|+]--|`--|--)\s*(.*)$/
  );
  if (m) {
    const name = cleanName(m[2]);
    if (!name) return null;
    return { prefixLen: m[1].length, name };
  }

  // Line with no connector but has leading pipes/spaces — could be a
  // continuation line; skip it or treat as empty.
  // If it's the very first line (root), it might just be a bare name.
  return null;
}

function parseTree(input: string): { nodes: TreeNode[]; warnings: string[] } {
  const lines = input.split("\n");
  const nodes: TreeNode[] = [];
  const warnings: string[] = [];
  const stack: { depth: number; prefixLen: number; path: string }[] = [];

  for (let i = 0; i < lines.length; i++) {
    const rawLine = lines[i];
    if (!rawLine.trim()) continue;

    const parsed = parseLine(rawLine);
    if (!parsed) {
      // Could be a bare root name on the first non-empty line
      if (nodes.length === 0) {
        const name = cleanName(rawLine);
        if (name) {
          nodes.push({ name, path: name, type: "folder", depth: 0 });
          stack.push({ depth: 0, prefixLen: 0, path: name });
        }
      }
      continue;
    }

    const { prefixLen, name } = parsed;

    // Infer depth from prefix length relative to known levels.
    // We find the stack entry whose prefixLen is closest but <= to this one.
    let depth = 0;
    while (
      stack.length > 1 &&
      stack[stack.length - 1].prefixLen >= prefixLen
    ) {
      stack.pop();
    }
    depth = stack.length;

    const parentPath =
      stack.length > 0 ? stack[stack.length - 1].path : "";
    const path = parentPath ? `${parentPath}/${name}` : name;

    const isFolder =
      name.endsWith("/") ||
      rawLine.trimEnd().endsWith("/") ||
      !/\.[a-zA-Z0-9]{1,15}$/.test(name);

    nodes.push({
      name: name.replace(/\/$/, ""),
      path,
      type: isFolder ? "folder" : "file",
      depth,
    });

    if (isFolder) {
      stack.push({ depth, prefixLen, path: path.replace(/\/$/, "") });
    }
  }

  if (nodes.length === 0) {
    warnings.push(
      "No valid tree entries found. Make sure you paste a directory tree format."
    );
  }

  return { nodes, warnings };
}

// ---------------------------------------------------------------------------
// Shell Script Generator
// ---------------------------------------------------------------------------

function generateShellScript(
  nodes: TreeNode[],
  projectName: string
): string {
  const lines: string[] = [
    "#!/bin/bash",
    "# Generated by ScaffoldForge",
    `# Project: ${projectName}`,
    "",
    `mkdir -p "${projectName}"`,
  ];

  for (const node of nodes) {
    if (node.type === "folder") {
      lines.push(`mkdir -p "${node.path}"`);
    } else {
      lines.push(`touch "${node.path}"`);
    }
  }

  lines.push("", `echo "✅ Project '${projectName}' created successfully!"`);
  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// ZIP Generator
// ---------------------------------------------------------------------------

async function generateZip(
  nodes: TreeNode[],
  projectName: string
): Promise<Blob> {
  const zip = new JSZip();

  for (const node of nodes) {
    if (node.type === "folder") {
      zip.folder(node.path);
    } else {
      zip.file(node.path, "");
    }
  }

  return zip.generateAsync({ type: "blob", compression: "DEFLATE" });
}

// ---------------------------------------------------------------------------
// Example tree
// ---------------------------------------------------------------------------

const EXAMPLE = `coldforge/
├── backend/
│   ├── src/
│   │   ├── api/
│   │   │   ├── v1/
│   │   │   │   ├── auth/
│   │   │   │   ├── domains/
│   │   │   │   ├── mailboxes/
│   │   │   │   ├── campaigns/
│   │   │   │   ├── analytics/
│   │   │   │   ├── settings/
│   │   │   │   └── health/
│   │   ├── core/
│   │   │   ├── smtp/
│   │   │   │   ├── client.js
│   │   │   │   ├── queue.js
│   │   │   │   └── validator.js
│   │   │   ├── dns/
│   │   │   │   ├── spf.js
│   │   │   │   ├── dkim.js
│   │   │   │   └── dmarc.js
│   │   │   └── database/
│   │   │       ├── models/
│   │   │       └── migrations/
│   │   ├── services/
│   │   │   ├── cloudflare.js
│   │   │   ├── namecheap.js
│   │   │   └── hostinger.js
│   │   ├── workers/
│   │   │   ├── sender.js
│   │   │   ├── cleaner.js
│   │   │   └── reporter.js
│   │   └── config/
│   │       ├── index.js
│   │       ├── database.js
│   │       └── smtp.js
│   ├── tests/
│   ├── package.json
│   └── .env.example
│
├── frontend/
│   ├── src/
│   │   ├── components/
│   │   │   ├── layouts/
│   │   │   ├── dashboard/
│   │   │   ├── domains/
│   │   │   └── common/
│   │   ├── hooks/
│   │   ├── services/
│   │   ├── store/
│   │   ├── styles/
│   │   ├── App.js
│   │   └── index.js
│   ├── public/
│   ├── package.json
│   └── .env.example
│
├── docker/
│   ├── backend.Dockerfile
│   ├── frontend.Dockerfile
│   └── nginx.conf
│
├── infra/
│   ├── docker-compose.yml
│   ├── kubernetes/
│   └── scripts/
│
├── docs/
│   ├── api/
│   ├── deployment/
│   └── user-guide/
│
└── README.md`;

// ---------------------------------------------------------------------------
// Tree Preview Component (recursive-like, with connectors)
// ---------------------------------------------------------------------------

function TreePreview({ nodes }: { nodes: TreeNode[] }) {
  return (
    <div className="font-mono text-[13px] leading-6 select-text">
      {nodes.map((node, i) => {
        const isLast =
          i === nodes.length - 1 ||
          (i < nodes.length - 1 && nodes[i + 1].depth < node.depth);

        // Determine the connector lines for ancestors
        const segments: { char: string; active: boolean }[] = [];
        for (let d = 0; d < node.depth; d++) {
          // Check if any future node at this depth exists after this one
          let hasFutureSiblingAtDepth = false;
          for (let j = i + 1; j < nodes.length; j++) {
            if (nodes[j].depth === d) {
              hasFutureSiblingAtDepth = true;
              break;
            }
            if (nodes[j].depth < d) break;
          }
          segments.push({
            char: hasFutureSiblingAtDepth ? "│" : " ",
            active: hasFutureSiblingAtDepth,
          });
        }

        const connector = isLast ? "└── " : "├── ";

        return (
          <div
            key={`${node.path}-${i}`}
            className="flex items-center whitespace-nowrap"
          >
            {segments.map((seg, si) => (
              <span
                key={si}
                className={seg.active ? "text-zinc-600" : "text-transparent"}
              >
                {seg.char + "   "}
              </span>
            ))}
            <span className={node.type === "folder" ? "text-amber-400" : "text-zinc-500"}>
              {connector}
            </span>
            <span
              className={
                node.type === "folder"
                  ? "font-medium text-zinc-200"
                  : "text-zinc-400"
              }
            >
              {node.name}
            </span>
          </div>
        );
      })}
    </div>
  );
}

// ---------------------------------------------------------------------------
// Main Page
// ---------------------------------------------------------------------------

export default function Home() {
  const [structure, setStructure] = useState(EXAMPLE);
  const [projectName, setProjectName] = useState("coldforge");
  const [isGenerating, setIsGenerating] = useState(false);
  const [generated, setGenerated] = useState(false);
  const [copiedField, setCopiedField] = useState<string | null>(null);
  const [isDragging, setIsDragging] = useState(false);
  const [outputFormat, setOutputFormat] = useState<"zip" | "sh">("zip");
  const [templateSearch, setTemplateSearch] = useState("");
  const [selectedTemplate, setSelectedTemplate] = useState<string | null>(null);
  const textareaRef = useRef<HTMLTextAreaElement>(null);

  const { nodes, warnings } = useMemo(() => parseTree(structure), [structure]);

  const folders = useMemo(() => nodes.filter((n) => n.type === "folder"), [nodes]);
  const files = useMemo(() => nodes.filter((n) => n.type === "file"), [nodes]);

  const rootName = useMemo(() => {
    if (nodes.length === 0) return projectName;
    return nodes[0].name;
  }, [nodes, projectName]);

  const effectiveName = projectName || rootName;

  const filteredTemplates = useMemo(() => {
    if (!templateSearch) return templates;
    const q = templateSearch.toLowerCase();
    return templates.filter(
      (t) =>
        t.name.toLowerCase().includes(q) ||
        t.tags.some((tag) => tag.includes(q)) ||
        t.description.toLowerCase().includes(q)
    );
  }, [templateSearch]);

  function handleSelectTemplate(template: (typeof templates)[number]) {
    setStructure(template.tree);
    const firstName = template.tree.split("\n")[0]?.trim().replace(/\/$/, "");
    if (firstName) setProjectName(firstName);
    setSelectedTemplate(template.id);
    setGenerated(false);
  }

  function handleExample() {
    setStructure(EXAMPLE);
    setProjectName("coldforge");
    setGenerated(false);
  }

  function handleClear() {
    setStructure("");
    setProjectName("");
    setGenerated(false);
  }

  async function handleDownload() {
    if (!nodes.length) return;
    setIsGenerating(true);

    try {
      if (outputFormat === "sh") {
        const script = generateShellScript(nodes, effectiveName);
        const blob = new Blob([script], { type: "text/x-shellscript" });
        downloadBlob(blob, `${effectiveName}.sh`);
      } else {
        const blob = await generateZip(nodes, effectiveName);
        downloadBlob(blob, `${effectiveName}.zip`);
      }
      setGenerated(true);
    } finally {
      setIsGenerating(false);
    }
  }

  async function handleCopy(format: "tree" | "shell") {
    let text: string;
    if (format === "tree") {
      // Reconstruct the tree from parsed nodes
      text = structure;
    } else {
      text = generateShellScript(nodes, effectiveName);
    }
    await navigator.clipboard.writeText(text);
    setCopiedField(format);
    setTimeout(() => setCopiedField(null), 2000);
  }

  // Drag and drop handlers
  const handleDragOver = useCallback((e: React.DragEvent) => {
    e.preventDefault();
    e.stopPropagation();
    setIsDragging(true);
  }, []);

  const handleDragLeave = useCallback((e: React.DragEvent) => {
    e.preventDefault();
    e.stopPropagation();
    setIsDragging(false);
  }, []);

  const handleDrop = useCallback(
    (e: React.DragEvent) => {
      e.preventDefault();
      e.stopPropagation();
      setIsDragging(false);

      const file = e.dataTransfer.files[0];
      if (file) {
        const reader = new FileReader();
        reader.onload = (event) => {
          const text = event.target?.result;
          if (typeof text === "string") {
            setStructure(text);
            setGenerated(false);
            // Try to infer project name from first line
            const firstLine = text.split("\n")[0].trim();
            const inferred = cleanName(firstLine).replace(/\/$/, "");
            if (inferred) setProjectName(inferred);
          }
        };
        reader.readAsText(file);
      }
    },
    []
  );

  return (
    <main className="min-h-screen bg-[#09090b] text-white">
      {/* Header */}
      <header className="border-b border-white/10 bg-[#09090b]/90 backdrop-blur">
        <div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-5">
          <div className="flex items-center gap-3">
            <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-emerald-500 font-black text-black">
              SF
            </div>
            <div>
              <h1 className="font-mono text-lg font-bold">ScaffoldForge</h1>
              <p className="text-xs text-zinc-500">
                Project structure generator
              </p>
            </div>
          </div>
          <div className="hidden rounded-full border border-white/10 bg-white/[0.03] px-4 py-2 text-xs text-zinc-400 sm:block">
            Paste → Preview → Download
          </div>
        </div>
      </header>

      <div className="mx-auto max-w-7xl px-6 py-10">
        {/* Hero */}
        <section className="mb-10">
          <div className="mb-4 inline-flex rounded-full border border-emerald-500/20 bg-emerald-500/10 px-3 py-1 text-xs font-medium text-emerald-400">
            Developer Tool
          </div>
          <h2 className="max-w-3xl text-4xl font-black tracking-tight sm:text-6xl">
            Turn your project tree into a{" "}
            <span className="text-emerald-400">ready-to-use template.</span>
          </h2>
          <p className="mt-5 max-w-2xl text-lg leading-8 text-zinc-400">
            Paste a directory structure and ScaffoldForge automatically creates
            the folders and files, then packages everything into a downloadable
            ZIP or shell script.
          </p>
        </section>

        {/* Template Browser */}
        <section className="mb-8">
          <div className="mb-4 flex items-center justify-between">
            <div>
              <h3 className="text-lg font-bold">Start from a template</h3>
              <p className="mt-1 text-sm text-zinc-500">
                Pick a pre-built structure or start from scratch.
              </p>
            </div>
            <div className="relative">
              <input
                value={templateSearch}
                onChange={(e) => setTemplateSearch(e.target.value)}
                placeholder="Search templates..."
                className="w-48 rounded-xl border border-white/10 bg-black/30 px-4 py-2 pl-9 font-mono text-xs outline-none transition focus:border-emerald-500 focus:w-64"
              />
              <svg
                className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-zinc-500"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"
                />
              </svg>
            </div>
          </div>

          <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
            {filteredTemplates.map((template) => (
              <button
                key={template.id}
                onClick={() => handleSelectTemplate(template)}
                className={`group rounded-xl border p-4 text-left transition ${
                  selectedTemplate === template.id
                    ? "border-emerald-500/60 bg-emerald-500/10"
                    : "border-white/10 bg-white/[0.02] hover:border-white/20 hover:bg-white/[0.04]"
                }`}
              >
                <div className="mb-2 flex items-center gap-2">
                  <span className="text-sm font-semibold">{template.name}</span>
                  {selectedTemplate === template.id && (
                    <span className="rounded bg-emerald-500/20 px-1.5 py-0.5 text-[10px] text-emerald-400">
                      Active
                    </span>
                  )}
                </div>
                <p className="mb-3 text-xs leading-5 text-zinc-500 line-clamp-2">
                  {template.description}
                </p>
                <div className="flex flex-wrap gap-1">
                  {template.tags.map((tag) => (
                    <span
                      key={tag}
                      className="rounded bg-white/5 px-1.5 py-0.5 text-[10px] text-zinc-600"
                    >
                      {tag}
                    </span>
                  ))}
                </div>
              </button>
            ))}
            {filteredTemplates.length === 0 && (
              <div className="col-span-full rounded-xl border border-dashed border-white/10 p-8 text-center text-sm text-zinc-600">
                No templates match "{templateSearch}".
              </div>
            )}
          </div>
        </section>

        {/* Project settings */}
        <section className="mb-6 rounded-2xl border border-white/10 bg-white/[0.03] p-5">
          <div className="grid gap-5 md:grid-cols-[1fr_auto] md:items-end">
            <div>
              <label className="mb-2 block text-sm font-medium text-zinc-300">
                Project name
              </label>
              <input
                value={projectName}
                onChange={(e) => setProjectName(e.target.value)}
                className="w-full rounded-xl border border-white/10 bg-black/30 px-4 py-3 font-mono text-sm outline-none transition focus:border-emerald-500"
                placeholder="my-project"
              />
            </div>
            <div className="flex gap-2">
              <button
                onClick={handleExample}
                className="rounded-xl border border-white/10 px-4 py-3 text-sm font-medium text-zinc-300 transition hover:bg-white/5"
              >
                Example
              </button>
              <button
                onClick={handleClear}
                className="rounded-xl border border-white/10 px-4 py-3 text-sm font-medium text-zinc-300 transition hover:bg-white/5"
              >
                Clear
              </button>
            </div>
          </div>
        </section>

        {/* Warnings */}
        {warnings.length > 0 && (
          <div className="mb-6 rounded-xl border border-amber-500/20 bg-amber-500/10 px-5 py-4 text-sm text-amber-400">
            {warnings.map((w, i) => (
              <p key={i}>{w}</p>
            ))}
          </div>
        )}

        {/* Editor */}
        <section className="grid gap-6 lg:grid-cols-2">
          {/* Input */}
          <div
            className={`overflow-hidden rounded-2xl border bg-[#0d0d0f] transition-colors ${
              isDragging
                ? "border-emerald-500/60 bg-emerald-500/5"
                : "border-white/10"
            }`}
            onDragOver={handleDragOver}
            onDragLeave={handleDragLeave}
            onDrop={handleDrop}
          >
            <div className="flex items-center justify-between border-b border-white/10 px-5 py-4">
              <div>
                <h3 className="font-semibold">Project Structure</h3>
                <p className="mt-1 text-xs text-zinc-500">
                  {isDragging
                    ? "Drop a file to import"
                    : "Paste your tree or drag a file"}
                </p>
              </div>
              <div className="flex items-center gap-2">
                <button
                  onClick={() => handleCopy("tree")}
                  className="rounded-md bg-white/5 px-2 py-1 text-[10px] text-zinc-500 transition hover:bg-white/10 hover:text-zinc-300"
                  title="Copy tree"
                >
                  {copiedField === "tree" ? "✓ Copied" : "Copy"}
                </button>
                <span className="rounded-md bg-white/5 px-2 py-1 font-mono text-[10px] text-zinc-500">
                  TREE
                </span>
              </div>
            </div>

            <textarea
              ref={textareaRef}
              value={structure}
              onChange={(e) => {
                setStructure(e.target.value);
                setGenerated(false);
              }}
              spellCheck={false}
              className="h-[500px] min-h-[300px] w-full resize-y bg-[#080809] p-5 font-mono text-xs leading-6 text-zinc-300 outline-none"
              placeholder={`my-project/\n├── src/\n│   ├── index.js\n│   └── utils/\n├── tests/\n└── README.md`}
            />
          </div>

          {/* Preview */}
          <div className="overflow-hidden rounded-2xl border border-white/10 bg-[#0d0d0f]">
            <div className="flex items-center justify-between border-b border-white/10 px-5 py-4">
              <div>
                <h3 className="font-semibold">Preview</h3>
                <p className="mt-1 text-xs text-zinc-500">
                  Generated project structure
                </p>
              </div>
              <div className="flex gap-2">
                <span className="rounded-md bg-emerald-500/10 px-2 py-1 text-[10px] text-emerald-400">
                  {folders.length} folders
                </span>
                <span className="rounded-md bg-blue-500/10 px-2 py-1 text-[10px] text-blue-400">
                  {files.length} files
                </span>
              </div>
            </div>

            <div className="h-[500px] overflow-auto bg-[#080809] p-5">
              {nodes.length === 0 ? (
                <div className="flex h-full flex-col items-center justify-center gap-3 text-sm text-zinc-600">
                  <svg
                    className="h-12 w-12 opacity-30"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke="currentColor"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth={1.5}
                      d="M3 7v10a2 2 0 002 2h14a2 2 0 002-2V9a2 2 0 00-2-2h-6l-2-2H5a2 2 0 00-2 2z"
                    />
                  </svg>
                  <p>Your project preview will appear here.</p>
                  <p className="text-xs text-zinc-700">
                    Paste a tree structure or drag a file
                  </p>
                </div>
              ) : (
                <TreePreview nodes={nodes} />
              )}
            </div>
          </div>
        </section>

        {/* Action bar */}
        <section className="mt-6 rounded-2xl border border-white/10 bg-white/[0.03] p-6">
          <div className="flex flex-col items-center justify-between gap-5 sm:flex-row">
            <div>
              <p className="font-medium">Ready to generate?</p>
              <p className="mt-1 text-sm text-zinc-500">
                {folders.length} folders and {files.length} files will be
                created.
              </p>
            </div>
            <div className="flex w-full gap-3 sm:w-auto">
              {/* Format toggle */}
              <div className="flex rounded-xl border border-white/10 bg-black/30 p-1">
                <button
                  onClick={() => setOutputFormat("zip")}
                  className={`rounded-lg px-4 py-2.5 text-sm font-medium transition ${
                    outputFormat === "zip"
                      ? "bg-white/10 text-white"
                      : "text-zinc-500 hover:text-zinc-300"
                  }`}
                >
                  ZIP
                </button>
                <button
                  onClick={() => setOutputFormat("sh")}
                  className={`rounded-lg px-4 py-2.5 text-sm font-medium transition ${
                    outputFormat === "sh"
                      ? "bg-white/10 text-white"
                      : "text-zinc-500 hover:text-zinc-300"
                  }`}
                >
                  Shell
                </button>
              </div>

              <button
                onClick={handleDownload}
                disabled={!nodes.length || isGenerating}
                className="w-full rounded-xl bg-emerald-500 px-7 py-3.5 font-semibold text-black transition hover:bg-emerald-400 disabled:cursor-not-allowed disabled:opacity-40 sm:w-auto"
              >
                {isGenerating
                  ? "Generating..."
                  : outputFormat === "zip"
                    ? "Download ZIP"
                    : "Download .sh"}
              </button>
            </div>
          </div>

          {/* Copy shortcuts */}
          {nodes.length > 0 && (
            <div className="mt-4 flex gap-3 border-t border-white/10 pt-4">
              <button
                onClick={() => handleCopy("tree")}
                className="rounded-lg border border-white/10 px-3 py-1.5 text-xs text-zinc-500 transition hover:bg-white/5 hover:text-zinc-300"
              >
                {copiedField === "tree" ? "✓ Copied tree" : "Copy tree"}
              </button>
              <button
                onClick={() => handleCopy("shell")}
                className="rounded-lg border border-white/10 px-3 py-1.5 text-xs text-zinc-500 transition hover:bg-white/5 hover:text-zinc-300"
              >
                {copiedField === "shell" ? "✓ Copied script" : "Copy shell script"}
              </button>
            </div>
          )}
        </section>

        {generated && (
          <div className="mt-4 rounded-xl border border-emerald-500/20 bg-emerald-500/10 px-5 py-4 text-sm text-emerald-400">
            ✅ Project generated successfully. Your{" "}
            {outputFormat === "zip" ? "ZIP file" : "shell script"} is ready.
          </div>
        )}

        {/* Features */}
        <section className="mt-20 grid gap-4 md:grid-cols-4">
          {[
            [
              "01",
              "Paste any structure",
              "Use the familiar tree format you already use in docs.",
            ],
            [
              "02",
              "Instant preview",
              "Visual tree with connectors — see hierarchy at a glance.",
            ],
            [
              "03",
              "ZIP or Shell",
              "Download a ZIP archive or a ready-to-run bash script.",
            ],
            [
              "04",
              "Drag & drop",
              "Drop a text file or terminal output directly.",
            ],
          ].map(([number, title, description]) => (
            <div
              key={number}
              className="rounded-2xl border border-white/10 bg-white/[0.03] p-6"
            >
              <div className="mb-5 font-mono text-sm text-emerald-400">
                {number}
              </div>
              <h3 className="font-semibold">{title}</h3>
              <p className="mt-2 text-sm leading-6 text-zinc-500">
                {description}
              </p>
            </div>
          ))}
        </section>

        <footer className="mt-20 border-t border-white/10 py-8 text-center text-xs text-zinc-600">
          ScaffoldForge — Build your project structure faster.
        </footer>
      </div>
    </main>
  );
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  link.remove();
  URL.revokeObjectURL(url);
}
